const actionTypes = {
  SET_USER: 'SET_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  UPDATE_SERIES_LIST: 'UPDATE_SERIES_LIST',
  UPDATE_SERIES_ENTRIES: 'UPDATE_SERIES_ENTRIES',
  FETCHING: 'FETCHING',
  UPDATE_BOOK_DETAIL: 'UPDATE_BOOK_DETAIL',
}

export default actionTypes;